# a workflow that uses the if conditional to check if the github.ref 
# (the branch or tag ref that triggered the workflow run) matches 
# refs/heads/main in order to proceed with the following steps in the workflow would look something like this:

name: Conditional Statement
on: push
jobs:
  prod-check:
    name: test
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
    - name: stepname
      run: echo "I am executed"
