name: 'Git Action Demo'
# -- left navigation name in Actions page

on:
  push:
    branches:
    - "dev"
  pull_request:
  workflow_dispatch:


jobs:
  sayHello:
    runs-on: ubuntu-latest
    
    steps: 
    - name: runscript
      run:  echo "Hello There"
   
   sayBye:
    runs-on: ubuntu-latest
    
    steps: 
    - run:  echo "Food Bye!!! See you around"
