on:
  schedule:
  - cron: '0 * * * *'
  workflow_dispatch:

name: Passing Variable Values to another step

jobs:
  passing-values-bw-steps:
    runs-on: ubuntu-latest
    steps:
    - name: Create-Variables
      id: var_source
      run: |
       echo "::set-output name=var1_name::TechSckool"
       echo "::set-output name=var2_date::$(date +'%Y-%m-%d-%H-%M')"
    
    - name: Get-Variable-Value
      run: |
       echo ${{ steps.var_source.outputs.var1_name }}
       echo ${{ steps.var_source.outputs.var2_date }}
