name: Upload-logs

on:
  workflow_dispatch

jobs:
  testing-log-upload:
    runs-on: ubuntu-latest
    steps:
    - name: run-command
      run: echod test
    - name: upload-logs
      if: always()
      run: "I still got executed"
